steps:
  - id: "deploy send-email-function"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'gcloud functions deploy send-email-function --runtime=python38 --timeout=180 --region=us-central1 --trigger-topic=janium-send-email-topic --source=./janium_functions/send_email/send_email_function --entry-point=main --egress-settings=private-ranges-only --vpc-connector=staging-vpc-connector --set-env-vars=PROJECT_ID=foundation-staging-305217,DB_USER=gcf,DB_PASSWORD=$$DB_PASSWORD_SECRET,DB_PRIVATE_HOST=$$DB_PRIVATE_HOST_SECRET,DB_DATABASE=staging,SENDGRID_API_KEY=$$SENDGRID_API_KEY_SECRET,KENDO_API_KEY=$$KENDO_API_KEY_SECRET']
    secretEnv: ['DB_PASSWORD_SECRET', 'DB_PRIVATE_HOST_SECRET', 'SENDGRID_API_KEY_SECRET', 'KENDO_API_KEY_SECRET']

  - id: "deploy send-email-director-function"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'gcloud functions deploy send-email-director-function --runtime=python38 --timeout=180 --region=us-central1 --trigger-topic=janium-send-email-director-topic --source=./janium_functions/send_email/send_email_director --entry-point=main --egress-settings=private-ranges-only --vpc-connector=staging-vpc-connector --set-env-vars=PROJECT_ID=foundation-staging-305217,DB_USER=gcf,DB_PASSWORD=$$DB_PASSWORD_SECRET,DB_PRIVATE_HOST=$$DB_PRIVATE_HOST_SECRET,DB_DATABASE=staging,SENDGRID_API_KEY=$$SENDGRID_API_KEY_SECRET,KENDO_API_KEY=$$KENDO_API_KEY_SECRET']
    secretEnv: ['DB_PASSWORD_SECRET', 'DB_PRIVATE_HOST_SECRET', 'SENDGRID_API_KEY_SECRET', 'KENDO_API_KEY_SECRET']

availableSecrets:
  secretManager:
  - versionName: projects/foundation-staging-305217/secrets/staging_db_password/versions/latest
    env: 'DB_PASSWORD_SECRET'
  - versionName: projects/foundation-staging-305217/secrets/staging_db_private_host/versions/latest
    env: 'DB_PRIVATE_HOST_SECRET'
  - versionName: projects/foundation-staging-305217/secrets/sendgrid-api-key/versions/latest
    env: 'SENDGRID_API_KEY_SECRET'
  - versionName: projects/foundation-staging-305217/secrets/kendo-api-key/versions/latest
    env: 'KENDO_API_KEY_SECRET'