runtime: python38
# entrypoint: gunicorn -b :$PORT foundation_api:app --timeout=90
service: backend

runtime_config:
  python_version: 3

vpc_access_connector:
  name: projects/foundation-production/locations/us-west3/connectors/prod-vpc-connector

instance_class: F4