"""remove reply address from email config

Revision ID: 045881c3266f
Revises: 5bc4aab24374
Create Date: 2021-07-26 09:41:36.071127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '045881c3266f'
down_revision = '5bc4aab24374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_config', 'reply_to_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('reply_to_address', mysql.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
