"""add is dkim and is domain to email config

Revision ID: 05c7a4301934
Revises: bd0f3c0b21a0
Create Date: 2021-05-04 09:35:44.535584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c7a4301934'
down_revision = 'bd0f3c0b21a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('is_sendgrid_domain_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('email_config', sa.Column('is_ses_dkim_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('email_config', sa.Column('is_ses_domain_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_config', 'is_ses_domain_verified')
    op.drop_column('email_config', 'is_ses_dkim_verified')
    op.drop_column('email_config', 'is_sendgrid_domain_verified')
    # ### end Alembic commands ###
