"""rename ses_identity cols

Revision ID: 2296c6809f01
Revises: 6bed062a271f
Create Date: 2021-08-23 11:32:44.367983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2296c6809f01'
down_revision = '6bed062a271f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('is_ses_identity_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('email_config', sa.Column('is_ses_identity_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('email_config', 'is_ses_singler_sender_verified')
    op.drop_column('email_config', 'is_ses_singler_sender_requested')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_config', 'is_ses_identity_verified')
    op.drop_column('email_config', 'is_ses_identity_requested')
    # ### end Alembic commands ###
