"""rename forwarding rule col

Revision ID: 28ac4528fc31
Revises: 2296c6809f01
Create Date: 2021-08-23 11:35:56.466422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28ac4528fc31'
down_revision = '2296c6809f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('is_email_forwarding_rule_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('email_config', 'is_email_forward_verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_config', 'is_email_forwarding_rule_verified')
    # ### end Alembic commands ###
