"""add is_processed flag to contact_source

Revision ID: 403b0818c5c3
Revises: d0960277fa35
Create Date: 2021-06-08 12:55:05.234518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403b0818c5c3'
down_revision = 'd0960277fa35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_source', sa.Column('is_processed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_source', 'is_processed')
    # ### end Alembic commands ###
