"""remove updated_by in User_account_map

Revision ID: 4562a0eb5b7e
Revises: 31b4d3f85a59
Create Date: 2021-04-14 13:07:10.452196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4562a0eb5b7e'
down_revision = '31b4d3f85a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_account_map_ibfk_3', 'user_account_map', type_='foreignkey')
    op.drop_column('user_account_map', 'updated_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account_map', sa.Column('updated_by', mysql.VARCHAR(length=36), nullable=False))
    op.create_foreign_key('user_account_map_ibfk_3', 'user_account_map', 'user', ['updated_by'], ['user_id'])
    # ### end Alembic commands ###
