"""add dte_sender

Revision ID: 47660d11df63
Revises: 93191cd3031d
Create Date: 2021-08-19 16:55:54.199231

"""
import json
import os
import uuid

import sqlalchemy as sa
from alembic import op
from foundation_api.V1.sa_db import model
from sqlalchemy import (JSON, Boolean, Column, Computed, DateTime, ForeignKey,
                        Integer, PrimaryKeyConstraint, String, Table, Text,
                        create_engine, engine)
from sqlalchemy.sql import column, false, func, null, table, text, true

# revision identifiers, used by Alembic.
revision = '47660d11df63'
down_revision = '93191cd3031d'
branch_labels = None
depends_on = None

dte_sender = table('dte_sender',
    column('dte_sender_id', String),
    column('dte_sender_full_name', String),
    column('dte_sender_from_email', String),
    column('is_ses_dkim_requested', String),
    column('is_ses_dkim_verified', String),
    column('is_ses_domain_verified', String)
)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dte_sender',
    sa.Column('dte_sender_id', sa.String(length=36), nullable=False),
    sa.Column('dte_sender_full_name', sa.String(length=128), nullable=False),
    sa.Column('dte_sender_from_email', sa.String(length=128), nullable=False),
    sa.Column('is_ses_dkim_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_ses_dkim_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_ses_domain_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('dte_sender_id')
    )
    op.execute(
        dte_sender.insert().values(
            dte_sender_id=model.Dte_sender.unassigned_dte_sender_id,
            dte_sender_full_name='Unassigned Dte Sender',
            dte_sender_from_email='unassigned@janium.io',
            is_ses_dkim_requested=False,
            is_ses_dkim_verified=False,
            is_ses_domain_verified=False
        )
    )


    op.add_column('account', sa.Column('dte_sender_id', sa.String(length=36), nullable=False))
    op.execute("UPDATE account SET dte_sender_id='{}'".format(model.Dte_sender.unassigned_dte_sender_id))
    op.create_foreign_key('account_ibfk_4', 'account', 'dte_sender', ['dte_sender_id'], ['dte_sender_id'])
    # ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_ibfk_4', 'account', type_='foreignkey')
    op.drop_column('account', 'dte_sender_id')
    op.drop_table('dte_sender')
    ### end Alembic commands ###
