"""add messenger_origin_message to ulinc_campaign

Revision ID: 5bc4aab24374
Revises: 7d5c24253866
Create Date: 2021-07-20 12:09:43.774163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc4aab24374'
down_revision = '7d5c24253866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ulinc_campaign', sa.Column('messenger_origin_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ulinc_campaign', 'messenger_origin_message')
    # ### end Alembic commands ###
