"""add single_sender_bool_cols

Revision ID: 6bed062a271f
Revises: 47660d11df63
Create Date: 2021-08-20 10:43:38.528205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bed062a271f'
down_revision = '47660d11df63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('is_ses_singler_sender_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('email_config', sa.Column('is_ses_singler_sender_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
