"""add gmail forwarding confirmation code to email_config

Revision ID: 7a2fc8b13b1a
Revises: 28ac4528fc31
Create Date: 2021-08-26 14:06:17.117984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2fc8b13b1a'
down_revision = '28ac4528fc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('gmail_forwarding_confirmation_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_config', 'gmail_forwarding_confirmation_code')
    # ### end Alembic commands ###
