"""add payment_effective dates to account

Revision ID: ba0419e256f4
Revises: 045881c3266f
Create Date: 2021-07-26 09:48:48.212559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0419e256f4'
down_revision = '045881c3266f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('payment_effective_end_date', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP)'), nullable=True))
    op.add_column('account', sa.Column('payment_effective_start_date', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'payment_effective_start_date')
    op.drop_column('account', 'payment_effective_end_date')
    # ### end Alembic commands ###
