"""add columns to email config for ses integration

Revision ID: bd0f3c0b21a0
Revises: 220cd5796cd6
Create Date: 2021-05-03 09:30:29.895285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0f3c0b21a0'
down_revision = '220cd5796cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('from_address', sa.String(length=64), nullable=False))
    op.add_column('email_config', sa.Column('is_ses', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('email_config', sa.Column('is_smtp', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_config', 'is_smtp')
    op.drop_column('email_config', 'is_ses')
    op.drop_column('email_config', 'from_address')
    # ### end Alembic commands ###
