"""add is domain requested to email config

Revision ID: d0960277fa35
Revises: 7031472c3ce4
Create Date: 2021-05-07 10:16:31.757029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0960277fa35'
down_revision = '7031472c3ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
