"""remove inbound_parse_email from user

Revision ID: e685fce993a0
Revises: 7a2fc8b13b1a
Create Date: 2021-08-26 14:18:25.378137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e685fce993a0'
down_revision = '7a2fc8b13b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'parse_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('parse_email', mysql.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###
