"""remove self-referential updated_by in user table

Revision ID: f15c7e748e1d
Revises: 403b0818c5c3
Create Date: 2021-06-16 11:05:19.033592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f15c7e748e1d'
down_revision = '403b0818c5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'updated_by')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('updated_by', mysql.VARCHAR(length=36), nullable=False))
    # op.create_foreign_key('user_ibfk_1', 'user', 'user', ['updated_by'], ['user_id'])
    # ### end Alembic commands ###
