"""add is reply proxy and remove sendgrid id

Revision ID: f273754b7cd3
Revises: 05c7a4301934
Create Date: 2021-05-06 11:00:21.370527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f273754b7cd3'
down_revision = '05c7a4301934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('is_reply_proxy', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('email_config', 'sendgrid_sender_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('sendgrid_sender_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_column('email_config', 'is_reply_proxy')
    # ### end Alembic commands ###
