"""add account foreign key to email_config

Revision ID: f58b21af3230
Revises: 4562a0eb5b7e
Create Date: 2021-04-15 16:17:35.443511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58b21af3230'
down_revision = '4562a0eb5b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('account_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'email_config', 'account', ['account_id'], ['account_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_config', type_='foreignkey')
    op.drop_column('email_config', 'account_id')
    # ### end Alembic commands ###
